pillar-markup/Microdown

src/Microdown-Tests/MicInlineSplitterTest.class.st, src/Microdown-Tests/MicroDownParserTest.class.st, src/Microdown/MicAbstractInlineBlock.class.st, src/Microdown/MicAnchorReferenceInlineBlock.class.st, src/Microdown/MicAnnotationInlineBlock.class.st, src/Microdown/MicEnvironmentBlock.class.st
FIX:
- nested inline blocks in asPillar (+green test)
- blocks and inline blocks annotation `<? .. ?>` : parse arguments , asPillar is working + green test
=> Fix annotation blocks and annotation inline blocks

src/Microdown-Tests/MicInlineSplitterTest.class.st, src/Microdown/MicAbstractInlineBlock.class.st, src/Microdown/MicAnchorReferenceInlineBlock.class.st, src/Microdown/MicInlineEmphasisProcessor.class.st, src/Microdown/MicMathInlineBlock.class.st, src/Microdown/MicMonospaceInlineBlock.class.st, src/Microdown/MicRawInlineBlock.class.st
Add method isEvaluated
Override it for anchorReference, math, monospace, raw
Thus unevaluated inline blocks are not parsed inside
+ tests to prove unevaluation works (testMonospaceUnevaluated for instance)
=> Add isEvaluated method for inline blocks

src/Microdown-Pillar/MicAbstractBlock.extension.st, src/Microdown-Pillar/MicAbstractInlineBlockWithUrl.extension.st, src/Microdown-Tests/MicInlineSplitterTest.class.st, src/Microdown-Tests/MicParagraphBlockTest.class.st, src/Microdown/MicAbstractBlock.class.st, src/Microdown/MicAbstractDelimiter.class.st, src/Microdown/MicAbstractInlineBlock.class.st, src/Microdown/MicAbstractInlineBlockWithUrl.class.st, src/Microdown/MicInlineSplitter.class.st, src/Microdown/MicInlineSplitterOld.class.st
Just one fail for escaped formats in links like `[**name**](url)`
Now I use an openers stack and handle one delimiter after one another
=> New inline parsinig strategy

src/BaselineOfMicrodown/BaselineOfMicrodown.class.st
rich text composer. Dependencies are too broad to make microdown useful on its own. Reduced number of dependencies
=> Fix dependencies so microdown-pillar can be loaded without 

src/Microdown-PrettyPrinter-Tests/MicDumperTest.class.st, src/Microdown-Tests/MicInlineParserTest.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown-Tests/MicMicrodownTextualBuilderTest.class.st, src/Microdown-Tests/MicroDownInlineParserTest.class.st, src/Microdown/MicAnnotationCloserDelimiter.class.st, src/Microdown/MicAnnotationOpenerDelimiter.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st, src/Microdown/MicStartStopMarkupBlock.class.st
change markup of annotation by ?{ }? et fix tests to work if we change markup later.
I use ?{ instead of {? because with {? the parser give a MetaDataBlock.
=> markup annotation

src/Microdown-MicrodownRichTextComposer/MicRichTextComposer.class.st, src/Microdown-ResolvePath-Tests/MicResolvePathTest.class.st, src/Microdown-ResolvePath-Tests/package.st, src/Microdown-ResolvePath/MicResolvePath.class.st, src/Microdown-ResolvePath/package.st, src/Microdown-Tests/MicFigureBlockTest.class.st, src/Microdown-Tests/MicInlineParserTest.class.st, src/Microdown-Tests/MicroDownInlineParserTest.class.st, src/Microdown-Tests/MicroDownParserTest.class.st, src/Microdown/MicAbstractBlock.class.st, src/Microdown/MicCodeBlock.class.st, src/Microdown/MicElement.class.st, src/Microdown/MicFigureBlock.class.st, src/Microdown/MicInlineBlockWithUrl.class.st, src/Microdown/MicInlineElement.class.st, src/Microdown/MicInlineParser.class.st, src/Microdown/MicRootBlock.class.st, src/Microdown/MicroDownParser.class.st
- parent and properties push up in MicElement
- add parseFile method
- MicRoot stock the originPath
- MicFigure
- add isImageFile
- add isRelativeFilePath
- add new visitor MicResolvePath
- make visitFigure of MicRichTextComposer more robust
=> Resolve path of figure

src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicRichTextTable.class.st, src/Microdown-RichTextComposer/MicRichTextTableDataSource.class.st
This should implement a discount version of table rendering.
It create a morph table and render it as a form.
Example:
```smalltalk
src := '
Yay, rendering tables in rich text
| AAA | $B_j$ | _CCC_ |
|---|---|---|
|![](https://pharo.org/web/files/pharo-logo-small.png)|**bar**| stuff|
|$a^{b^x}$| xxxx |$\frac{a+b}{c+z}$|
That is just awesome
'.
MicRichTextComposer microdownAsRichText: src.
```
=> Fixes #233. Rendering of tables (as forms) in rich text.

src/Microdown-Tests/MicroDownParserTest.class.st, src/Microdown/MicTableBlock.class.st
Allowed pipe `|` to be escaped in tables using `\|`. Also included a test to support it.
=> Fixes #277.

src/Microdown-RichTextComposer-Tests/MicCodeSemanticActionTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicSemanticAction.class.st
In addition I feel it fixes https://github.com/pillar-markup/Microdown/issues/276#issuecomment-962587695.
=> Fixes #72 - Browsing comment of RBPatternVariableNode raises a syntax Error?

src/BaselineOfMicrodown/BaselineOfMicrodown.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st
This PR updates the baseline to ensure PillarCore is loaded.
It also reverts MicRichTextComposer to use codeStyler and textStyler
=> 318 ci is no longer green

src/Microdown/MicBoldFormatBlock.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st, src/Microdown/MicroDownParser.class.st
Someone had left a category name 'utilscaca' in the code. Renamed. Also the main Pharo have been pushing for consistent spelling of 'utilities' rather than 'util' or 'utils'. Fixed those also for combined names like 'private utilities'.
=> Fixes some category naming issues

src/Microdown-RichTextComposer/MicTextStyler.class.st, src/Microdown/MicInlineParser.class.st
Using the contents of `gen_refactoringframework.md`, and the call `Microdown parse: contents`.
Timing using:
```smalltalk
((1 to: 25) collect: [:dummy | Time microsecondsToRun: [Microdown parse: contents]]) min
```
Initial result: 305,196 µs
read: non-recursive: 292,053 µs (non-significant - kudos Pharo!)
making identifyMarkupFor: check only in relevant cases : 53,211 µs
Speedup: 5+ times.
Other speedup might be possible, but using `TimeProfiler` there are no 
obviously bad code to attack (few percent gain).
Sadly the `TimeeProfiler` points to `SHTextStyler`, the code styler for pharo.
Rendering all code as raw text gives a speedup on rendering time of 8+ times.
=> Fixes #376 speed is becoming an issue

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st
=> Fixes #388. TextComposer should be able to do inputFile 

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-Tests/MicPharoImageResourceReferenceTest.class.st, src/Microdown/MicPharoImageResourceReference.class.st
Enabled the loadMicrodown method, allowing microdown: `{!inputFile|path=pharo:/Class/method/arg1/arg2!}`, that is to include computed microdown to be input into a microdown document.
=> Fixes #398 mic pharo image resource reference only handles images

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicroDownParser.extension.st
FIxes #402
Just copies the raw body onto the output canvas. Added a few tests in addition
=> Fixes #402 mic rich text composer does not handle raw

src/Microdown/MicFileResourceReference.class.st
It would be useful with a windows machine in the CI - dreams are free...
=> Fixes #391 - failing MicFileResourceReference test on windows

src/Microdown-Tests/MicInlineParserTest.class.st, src/Microdown/MicAnnotationBlock.class.st, src/Microdown/MicInlineBlockWithUrl.class.st, src/Microdown/MicInlineElement.class.st, src/Microdown/MicInlineParser.class.st, src/Microdown/MicMathInlineBlock.class.st, src/Microdown/MicMonospaceFormatBlock.class.st, src/Microdown/MicRawBlock.class.st
- The escape character is \
- One can escape any character which is part of a Microdown delimiter
- Escaping and Descaping should be handled uniformly across all inline blocks
- No paragraph block should start with the escape charager (true now) - this means that an escaped paragraph block starter will cause the paragraph to be Paragraph, and the escape will then be part of the inline parser (as intended).
- MicInlineParser>>#parse: will convert all \X | X in Delimiter to characters in Unicode PUB 16 area, more precisely U10A000 + X asInteger.
- Notice, the conversion happens before parsing the inner text, so there is no change of text length.
- MicInlineElement>>cleanString converts all U10Axxx to original characters.
=> Fixes: 442 table does not work well with nested  in monospace 

src/Microdown-DocumentBrowser-Tests/MicGitHubRessourceReferenceTest.class.st, src/Microdown-DocumentBrowser/MicOpenDocumentBrowserCommand.class.st, src/Microdown-HTMLExporter-Tests/MicCSSProviderTest.class.st, src/Microdown-HTMLExporter-Tests/MicHTMLBrushTest.class.st, src/Microdown-HTMLExporter-Tests/MicHTMLCanvasTest.class.st, src/Microdown-HTMLExporter-Tests/MicHTMLTagTest.class.st, src/Microdown-HTMLExporter/MicCSSProvider.class.st, src/Microdown-Tests/MicLinkBlockTest.class.st, src/Microdown/MicAbstractBlock.class.st, src/Microdown/MicAnnotationBlock.class.st, src/Microdown/MicCodeBlock.class.st, src/Microdown/MicSameStartStopMarkupBlock.class.st
There are some of the problems which are not in the microdown project, but in its dependencies.
- testNoLeadingOrTrailingSpacesInCategoryNames - is caused by 
`DTDEntity->#'private ' XMLEnumerationAttributeValidator->#'private ' BaselineOfXMLParser->#'prerequisites ' XMLHTTPZincRequest->#'private ' XMLHTTPDecompressingReadStreamAdapterFactory class->#'private ' SAX2Parser class->#'private '`
- testNoUncategorizedMethods - microdown parts fixed in 3255d96b87ccf1e3a5fb47d1e7a1bb0113044adf, but the following remains: `PRFigure PRMetadata PRParameters class StDebuggerCommand`
- testMethodsContainNoHalt fixed. There was a number of obsolete methods which contained a halt to alert if called. Now they are deleted.
- testObsoleteClasses  - when running in local image, I get: …
=> Fixes #470 integration is failing 

src/Microdown-RichTextComposer-Tests/MicCodeStylerSpecTest.class.st, src/Microdown-RichTextComposer-Tests/MicDynamicTextStylerTest.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextFormatConfigurationTest.class.st, src/Microdown-RichTextComposer/MicCodeStylerSpec.class.st, src/Microdown-RichTextComposer/MicDynamicTextStyler.class.st, src/Microdown-RichTextComposer/MicRichTextCanvas.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicRichTextFormatConfiguration.class.st, src/Microdown-RichTextComposer/MicTextStyler.class.st, src/Microdown-RichTextComposer/MicrodownVisitor.extension.st, src/Microdown-RichTextComposer/Text.extension.st
This PR is cool, it allow us to adjust font and spacings of the RichTextComposer from within Microdown using an extension.
To get really large header level 1, and larger body font you can write:
```
{!richtext|headerFont1=Lucida Grande;72&bodyFont=Lucida Grande;24!}
and large body
```
I think it will be rather useful for slides
=> Fixes #411 tailoring richtext composer using microdown

src/Microdown-Tests/MicFileResourceReferenceTest.class.st, src/Microdown/MicFileResourceReference.class.st
@Ducasse - I think this PR fixes the issue we found yeasterday
'/Users/kasper/tmp' asFileReference asMicResourceReference uri withRelativeReference: 'foo/my.md' now returns 'file:///Users/kasper/tmp/foo/my.md'.
Fix is done in `MicFileResourceReference>>#fromFileRef:`
=> Fixes #519 Microdown directory resolution

src/Microdown-HTMLExporter/MicHTMLStylerOpenCommand.class.st, src/Microdown-Tests/MicEnvironmentBlockTest.class.st, src/Microdown-Tests/MicResourceReferenceTest.class.st, src/Microdown-Tests/MicrodownParserTest.class.st, src/Microdown/MicAnchorReferenceBlock.class.st
Yay - a meta programming exercise - fixed these methods
```smalltalk
(((RPackage organizer packages select: [ :p | 
p name beginsWith: 'Microdown' ]) collect: #classes) flattened 
collect: [ :cl | cl methodDictionary values ]) flattened 
select: [ :cm | 
cm ast allChildren anySatisfy: [ :e | 
(e isLiteralNode and: [ e value isString ]) and: [ 
e value asLowercase includesSubstring: '.mic' ] ] ]
```
=> Changed all .mic to .md

src/Microdown-RichTextComposer/MicSmalltalkTextStyler.class.st
Fixes #557, dark theme. Also catches theme changes.
SHRBTextStyler used a several class instance variables which was not handled correctly in the subclass.
=> Fixes #557, dark theme. Also catches theme changes

src/Microdown-HTMLExporter-Tests/MicHTMLVisitorTest.class.st, src/Microdown-LaTeXExporter-Tests/MicSBALaTeXWriterTest.class.st, src/Microdown-PrettyPrinter-Tests/MicTextualMicrodownExporterTest.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-Tests/MicMicrodownSnippetFactory.class.st, src/Microdown/MicrodownParser.class.st
Notice that this change impacted a number of tests in latex and html. Before it was possible to write nested lists using tabs rather than space, not anymore. 
Personally I think it was a good idea anyways as it is easier to see that the indentation of nested lists fits the rules of the parser.
=> Fixes #556, allowing tabs to be preserved in code blocks (and elsewhere)

src/Microdown-Tests/MicrodownInlineParserTest.class.st, src/Microdown/MicInlineParser.class.st, src/Microdown/MicMathInlineBlock.class.st, src/Microdown/MicMonospaceFormatBlock.class.st, src/Microdown/MicRootBlock.class.st
This fix seems to patch the inline parser. 
I did not load the full microdown at this one, so full tests pending
=> Fixes #567, MicMathInlineBlock comment does not render

src/Microdown-RichTextComposer/MicRichTextComposer.class.st
It was a known issue which surfaced in a new way.
There will now ne rendered a space before and after an image when rendered asText.
=> This patches the error of rubrics

src/Microdown-LaTeXExporter-Tests/MicLaTeXWriterTest.class.st, src/Microdown-LaTeXExporter-Tests/MicSBALaTeXWriterTest.class.st, src/Microdown-LaTeXExporter/MicLaTeXWriter.class.st
While converting books from Pillar to Microdown, I also checked that we get the same result with the Microdown file than the Pillar file. But there was a problem with the table which was put next to the text before them. So I added a newLine in order to get the good result when we get the LaTeX file to pdf.
=> Adding a newLine before each table when converted from Microdown to LaTeX

src/Microdown-HTMLExporter-Tests/MicHTMLVisitorTest.class.st, src/Microdown-PrettyPrinter-Tests/MicTextualMicrodownExporterTest.class.st, src/Microdown-Tests/MicCodeBlockTest.class.st, src/Microdown-Tests/MicEnvironmentBlockTest.class.st, src/Microdown-Tests/MicrodownParserTest.class.st, src/Microdown/MicCodeBlock.class.st, src/Microdown/MicEnvironmentBlock.class.st, src/Microdown/MicrodownParser.class.st, src/Microdown/String.extension.st
Made a test similar to original proposal.
Implemented as suggested in the issue.
Fixed a number of tests that depended on near empty lines with just a single tab in the line.
=> FIxes 543 nice environment
