src/Microdown-Pillar/MicAnnotationInlineBlock.extension.st, src/Microdown/MicArgumentsSplitter.class.st, src/Microdown/MicCodeBlock.class.st, src/Microdown/MicEnvironmentBlock.class.st, src/Microdown/MicFigureInlineBlock.class.st
Change MicArgumentsSplitter API to ask him his firstTag, name or arguments directly!
=> Improve arguments splitter

src/Microdown-Tests/MicroDownParserTest.class.st
=> Change testEnvironmentCitationWithArguments

src/BaselineOfMicrodown/BaselineOfMicrodown.class.st
Reverts pillar-markup/MicroDown#58
=> Revert "Fix dependencies so microdown-pillar can be loaded without "

src/BaselineOfMicrodown/BaselineOfMicrodown.class.st
Another attempt to fix the Microdown baseline to not pull in all of Pillar
=> Fix baseline dependencies

src/Microdown-PrettyPrinter-Tests/MicDumperTest.class.st, src/Microdown-PrettyPrinter/MicDullDumper.class.st, src/Microdown-PrettyPrinter/MicTextualMicrodownExporter.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown-Tests/MicMicrodownTextualBuilderTest.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st
before to https://github.com/SquareBracketAssociates/Booklet-PharoWithStyle we obtain SquareBracketAssociates/Booklet-PharoWithStyle.
Now we obtain https://github.com/SquareBracketAssociates/Booklet-PharoWithStyle
=> Correction builder to link and figure

src/Microdown-Pillar-Tests/MicSurfacicMicrodownToPillarTest.class.st
remove tests on script parameters because there is not parametersBlock in Microdown
=> remove tests on script parameters

src/Microdown-PrettyPrinter-Tests/MicTextualMicrodownExporterTest.class.st, src/Microdown-PrettyPrinter/MicTextualMicrodownExporter.class.st, src/Microdown-Tests/MicInlineSplitterTest.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown-Tests/MicroDownInlineParserTest.class.st, src/Microdown/MicInlineElement.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st
- put tests in differents protocols
- extract method fixBlockWitoutMicText
- add wrappedElement with tests
=> extract method fixBlockWitoutMicText

src/Microdown-Pillar-Tests/MicCodeBlockTest.extension.st, src/Microdown-Pillar/MicCodeBlock.extension.st
change asPillar if language is absent and that the first key has a value empty or nil then asPillar put in prBlock language->firstkey
=> asPillar MicCodeBlock

src/Microdown/MicMicrodownTextualBuilder.class.st
the error was when we have a object which is not a String
=> correct codeBlock builder

src/Microdown-Tests/MicroDownParserTest.class.st, src/Microdown/MicroDownParser.class.st
resolve the probleme when parse: totaly break when a Text is passed as argument
=> parse: can parse text as arument

src/Microdown-PrettyPrinter-Tests/MicTextualMicrodownExporterTest.class.st, src/Microdown-PrettyPrinter/MicTextualMicrodownExporter.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st, src/Microdown/MicrodownVisitor.class.st
put newLine before header, paragraph, figure, list and codeblock and correct factory method of these elements.
=> put newLine before header, paragraph, figure, list and codeblock

src/Microdown-PrettyPrinter/MicTextualMicrodownExporter.class.st, src/Microdown-convert/ConvertPillarToMicrodown.class.st, src/Microdown/MicAbstractMicrodownTextualBuilder.class.st
the PR has a link with an orther PR in Pillar with the same name
=> Convert pillar book to microdown book

src/Microdown-Converter/ConvertPillarToMicrodown.class.st, src/Microdown-PrettyPrinter-Tests/MicTextualMicrodownExporterTest.class.st, src/Microdown-PrettyPrinter/MicTextualMicrodownExporter.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown/MicFormatBlock.class.st, src/Microdown/MicInlineBlockWithUrl.class.st, src/Microdown/MicInlineParser.class.st, src/Microdown/MicrodownBackSlasher.class.st
- add a backslasher to export in Microdown
- improve the converter
=> add a backslasher to export in Microdown

src/Microdown-Evaluator-Tests/MicCodeblockEvaluatorTest.class.st, src/Microdown-Transformer-Tests/MicFileInclusionTest.class.st, src/Microdown-Transformer-Tests/MicNodeTransformerTest.class.st, src/Microdown-Transformer/MicFileInclusion.class.st, src/Microdown-Transformer/MicNodeTransformer.class.st
the prev visit: method is now named visitAll: and start: is named visit:
=> change start: to visit:

src/Microdown-MicrodownRichTextComposer/MicRichTextComposer.class.st, src/Microdown/MicHTTPResource.class.st, src/Microdown/MicResourceReference.class.st, src/Microdown/ZnUrlCopy.class.st
I arrived to these changes after errors on MicroEd "Render" button on the example document.
=> Two changes

src/Microdown-MicrodownRichTextComposer/MicRichTextComposer.class.st, src/Microdown-MicrodownRichTextComposer/MicRichTextComposerTest.class.st, src/Microdown/MicSameStartStopMarkupBlock.class.st
There is still one skipped test having to do with problems in the image resolver. I left it skipping for now
=> 217 rich text composer has skipped tests

src/Microdown-MicrodownRichTextComposer/MicDisplayer.class.st, src/Microdown-MicrodownRichTextComposer/MicRichTextComposer.class.st, src/Microdown-MicrodownRichTextComposer/MicRichTextComposerTest.class.st, src/Microdown-MicrodownRichTextComposer/MicroDownParser.extension.st, src/Microdown-Tests/MicCitationBlockTest.class.st, src/Microdown-Tests/MicElementTest.class.st, src/Microdown-Tests/MicFootnoteBlockTest.class.st, src/Microdown-Tests/MicInputfileBlockTest.class.st, src/Microdown-Tests/MicMathBlockTest.class.st, src/Microdown-Tests/MicMicroDownSnippetFactory.class.st, src/Microdown-Tests/MicMicrodownTextualBuilderTest.class.st, src/Microdown-Tests/MicPathResolverTest.class.st, src/Microdown-Tests/MicroDownInlineParserTest.class.st, src/Microdown-Tests/MicroDownParserTest.class.st, src/Microdown/MicAbstractBlock.class.st, src/Microdown/MicAbstractMicrodownTextualBuilder.class.st, src/Microdown/MicArgumentsSplitter.class.st, src/Microdown/MicInputfileBlock.class.st, src/Microdown/MicPathResolver.class.st, src/Microdown/MicroDownParser.class.st, src/Microdown/Microdown.class.st
Reverts pillar-markup/Microdown#220
=> Revert "Rename classes (fix capitalisation)"

README.md
=> 229 improve readme

src/Microdown/MicAnnotatedBlock.class.st, src/Microdown/MicHorizontalLineBlock.class.st
This PR removes some methods that have an equal definition in the superclass
=> Remove-unnecessary-methods

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown/MicCodeBlock.class.st
This PR fixes a number of issues: #27, #33, #67 and #107
=> Misc fixes

src/Microdown-HTMLExporter/MicHTMLCanvas.class.st, src/Microdown-PrettyPrinter-Tests/MicRealDumperTest.class.st, src/Microdown-PrettyPrinter/MicRealDumper.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicRichTextTable.class.st, src/Microdown-RichTextComposer/MicRichTextTableDataSource.class.st, src/Microdown-Tests/MicPathResolverTest.class.st
I got some errors from the release test suite. This PR should solve them.
=> Microdown release errors fix

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown/MicAbsoluteResource.class.st, src/Microdown/MicHTTPResource.class.st, src/Microdown/MicPharoResource.class.st, src/Microdown/MicRelativeResource.class.st, src/Microdown/MicZinkPathResolver.class.st, src/Microdown/Microdown.class.st
- Added more facade methods on class side of key classes
- tried to make some method names more consistent 
- added an examples smoke test for RichTextComposer
- Beautiful comments settings removed from RichTextComposer
=> Cleanup and beautify

src/Microdown/MicPharoResource.class.st
This should fix a stupid error in MicPharoResource
=> fixes #296 and gives a better example in class comment

src/Microdown-Tests/MicInlineParserTest.class.st
=> "access" -> "accessing"

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown/MicrodownVisitor.class.st
Simple implementation of quote block rendering, and a test for same.
=> fixes #294. Simple presentation of quote, and test to make sure it works

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st
See comment in issue #292 about what is the problem and its hacky solution.
=> Hack that fixes issue #292

src/Microdown-Tests/MicEnvironmentBlockTest.class.st, src/Microdown/MicEnvironmentBlock.class.st, src/Microdown/MicParagraphBlock.class.st
It turned out that Paragraphs had an error in its accept next line. Simple fix.
=> 329 environment parses wrong

src/Microdown-RichTextComposer/MicRichTextComposer.class.st
=> redone RichTextComposer examples.

src/Microdown-RichTextPresenter-Tests/MicTextPresenterTest.class.st, src/Microdown-RichTextPresenter-Tests/MicrodownPresenterTest.class.st, src/Microdown-RichTextPresenter-Tests/MicrodownSpecComponentForTest.class.st, src/Microdown-RichTextPresenter-Tests/MicrodownSpecComponentTest.class.st, src/Microdown-RichTextPresenter-Tests/package.st, src/Microdown-RichTextPresenter/MicMorphicTextAdapter.class.st, src/Microdown-RichTextPresenter/MicScrolledTextMorph.class.st, src/Microdown-RichTextPresenter/MicTextPresenter.class.st, src/Microdown-RichTextPresenter/MicrodownPresenter.class.st, src/Microdown-RichTextPresenter/package.st
I have not updated the baseline to include it. That is on purpose as it is still a little unclear where is should end up in the grander scheme of things.
=> moved the presenter to its own package Microdown-RichTextPresenter

src/Microdown/ManifestMicrodown.class.st, src/Microdown/MicAbstractResolver.class.st, src/Microdown/MicFileResourceReference.class.st, src/Microdown/Microdown.class.st
Do not merge, this is just to make sure all still pass
=> 338 support for file host disappeared

src/BaselineOfMicrodown/BaselineOfMicrodown.class.st
=> tests should not be loaded in core group

src/Microdown-RichTextComposer/MicRichTextComposer.class.st
I have green now - lets see if it works here too
=> Fixes the latex problem due to codecogs service changed their syntax

src/Microdown-RichTextComposer/MicTextStyler.class.st
I left the code commented out so one can see what might be done
=> fixes #366 by commenting out the code

src/Microdown-RichTextComposer/MicTextStyler.class.st, src/Microdown-Tests/MicroDownInlineParserTest.class.st, src/Microdown/MicMonospaceFormatBlock.class.st
One change and three tests added
=> Fixes #341 inline code monospace does slash treatment wrong

src/Microdown-DocumentBrowser-Tests/MicGitHubAPITest.class.st, src/Microdown-DocumentBrowser-Tests/MicGitHubRessourceReferenceTest.class.st, src/Microdown-DocumentBrowser/MicGitHubAPI.class.st, src/Microdown-DocumentBrowser/MicGitHubAPIRateError.class.st, src/Microdown-DocumentBrowser/MicGitHubRessourceReference.class.st, src/Microdown/MicResourceReference.class.st
I will use this branch for Document browser development, and merge it into the dev branch to check that all tests are green.
=> Document browser development

src/Microdown-DocumentBrowser/MicGitHubRessourceReference.class.st, src/Microdown-DocumentBrowser/MicPharoCommentResourceReference.class.st, src/Microdown-Tests/MicResourceReferenceTest.class.st, src/Microdown/MicFileResourceReference.class.st, src/Microdown/MicHTTPResourceReference.class.st, src/Microdown/MicPharoImageResourceReference.class.st, src/Microdown/MicResourceReference.class.st
Fixes #383, removing unintended dependency
=> Fixes #383 using a simple subclass extension mechanism

src/Microdown-Tests/MicZincPathResolverTest.class.st, src/Microdown/FileReference.extension.st, src/Microdown/ManifestMicrodown.class.st, src/Microdown/MicAbsoluteResourceReference.class.st, src/Microdown/MicElement.class.st, src/Microdown/MicZincPathResolver.class.st, src/Microdown/Microdown.class.st, src/Microdown/ZnUrl.extension.st
Thanks for the suggestion @Ducasse
=> Fixes #384 improve microdown api for doing resolution

src/Microdown-Tests/MicHeaderBlockTest.class.st, src/Microdown/MicHeaderBlock.class.st
=> Fixes #375, header levels below 1 and above 6 disallowed

src/Microdown-MathFlaky-Tests/MicRichTextComposerTest.extension.st, src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st
There were a couple of issues in the richtext composer tests
=> Changes a couple of tests to use new math env syntax

src/Microdown-Tests/MicInlineParserTest.class.st, src/Microdown/MicInlineParser.class.st
Index out of range error fixed
=> Fixes 464 unfinished inline code/monospace block breaks inline parser

src/Microdown-Tests/MicInputFileResolverTest.class.st, src/Microdown/MicAbstractBlock.class.st, src/Microdown/MicInputFileResolver.class.st, src/Microdown/MicMicrodownTextualBuilder.class.st
The main part of the change are in pillar which i will do a PR.
=> Change done for the math support in the conversion from Pillar to Microdown

src/Microdown-Tests/MicMathBlockTest.class.st, src/Microdown/MicMathBlock.class.st
=> Fixes 474 multiline mathblock should handle latex comment

src/Microdown-DocumentBrowser/MicGitHubRessourceReference.class.st
I wish all issues was this simple :-)
=> Fixes #437 - isMicrodownOrFolder: is dead code

src/Microdown-DocumentBrowser-Tests/MicPharoPackageCommentResourceReferenceTest.class.st, src/Microdown-DocumentBrowser/MicAbstractBlock.extension.st, src/Microdown-DocumentBrowser/MicDocumentBrowser.class.st, src/Microdown-DocumentBrowser/MicOpenDocumentBrowserCommand.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextFormatConfigurationTest.class.st, src/Microdown-RichTextComposer/MicDynamicTextStyler.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicRichTextFormatConfiguration.class.st
This PR just concern the document browser
=> Merge of Document browser development

src/Microdown-Tests/MicrodownVisitorTest.class.st, src/Microdown/MicDocumentListBlock.class.st, src/Microdown/MicElement.class.st, src/Microdown/MicrodownVisitor.class.st
Added a test, and fixed the errors it found
=> Fixes #533 microdown visitors are unstable

src/Microdown-Agenda-Tests/MicAgendaGeneratorTest.class.st, src/Microdown-Agenda/MicAbstractComponentBlock.class.st, src/Microdown-Agenda/MicAgendaGenerator.class.st
but we generate a full HTML for the calendar + need to fix the test about the use of the template
=> Optimization of the generated calendar, now we need to have to template on local

src/Microdown-DocumentBrowser/MicDocumentBrowser.class.st
Fixes a update problem in Document browser sectioning
=> Changed saveNewSourceForSelectedDocument to fix selection issue

src/Microdown-DocumentBrowser-Tests/MicPharoPackageCommentResourceReferenceTest.class.st, src/Microdown-DocumentBrowser/MicDocumentBrowser.class.st, src/Microdown-DocumentBrowser/MicGitHubRessourceReference.class.st, src/Microdown-DocumentBrowser/MicPharoPackageCommentResourceReference.class.st
It now follows the same hierarchy as the packages and tags in the browser
=> Cleanup package comment resource

src/Microdown/MicrodownVisitor.class.st
I have made these change next to the comments of Kasper because i made a PR but i had not checked correctly the tests before doing it. Now all the tests are greens with the packages Microdown-Agenda and Microdown-Agenda-Tests.
=> Adding some methods from MicAgendaGenerator to MicrodownVisitor in order to get all the tests green

src/Microdown-RichTextComposer-Tests/MicCenterAlignmentBlockTest.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer-Tests/MicRightAlignmentBlockTest.class.st, src/Microdown-RichTextComposer/MicCenterAlignmentBlock.class.st, src/Microdown-RichTextComposer/MicRichTextComposer.class.st, src/Microdown-RichTextComposer/MicRightAlignmentBlock.class.st, src/Microdown-RichTextComposer/MicrodownVisitor.extension.st
There is only one l in align - not two...
=> Fixes #536 - Spelled align right

src/Microdown/MicRootBlock.class.st
=> Fix: #570 and  https://github.com/pillar-markup/pillar/issues/574

src/Microdown-HTMLExporter-Tests/MicHTMLConfigurationTest.class.st, src/Microdown-HTMLExporter/MicHTMLVisitor.class.st
I removed the defaultScriptLanguage.
=> Removing dependencies to pillar.

src/Microdown-Tests/MicrodownInlineParserTest.class.st, src/Microdown/MicInlineParser.class.st, src/Microdown/MicMathInlineBlock.class.st, src/Microdown/MicMonospaceFormatBlock.class.st, src/Microdown/MicRootBlock.class.st
Merging removing pillar dev + inline parse fix into master
=> Merging removing pillar dev + inline parse fix into master

src/Microdown-DocumentBrowser/MicDocumentBrowser.class.st
=> Scroll document browser to first line

src/Microdown-DocumentBrowser/MicDocumentBrowser.class.st, src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st
And in addition, source which cannot be edited is shown in a different color and editing is disabled
=> 598 document browser should show if source is dirty or not

src/Microdown-PrettyPrinter-Tests/MicDumperTest.class.st, src/Microdown-PrettyPrinter/MicRealDumper.class.st, src/Microdown/MicFormatBlock.class.st, src/Microdown/MicParagraphBlock.class.st
- Cleaning Dumper for boldFormat
- Enhancing API with textElements: and textElement:
- fixing all the tests related to boldFormat.
- Next italic and others
=> 572 mic real dumper is broken

src/Microdown-Tests/MicStringExtensionTest.class.st, src/Microdown/MicCodeBlock.class.st, src/Microdown/MicListBlock.class.st, src/Microdown/String.extension.st
Fixes #597,  fragile handling of tabs in the beginning of paragraph level blocks
=> Fixes #597, some class comments did not parse.

src/Microdown-RichTextComposer-Tests/MicRichTextComposerTest.class.st, src/Microdown-RichTextComposer/OrderedCollection.extension.st
And an error because a test was depending on an extension in DocBrowser package
=> Fixes 630 crAfterHeader   dnu
